
/* AGGREGATE FUNCTION 
   AVG(),
   FIRST(),
   LAST(),
   MAX(),
   MIN(),
   SUM()
   */

   -- AVG() FUNCTION
   SELECT AVG(FIYAT) AS ORTFIYAT FROM tablo_adi

   --FIRST() FUNCTION 
   SELECT FIRST(MLZADI) FROM tablo_adi

   --LAST() FUNCTION
   SELECT LAST(MLZADI) FROM tablo_adi

   --MAX() FUNCTION
   SELECT MAX(FIYAT)  AS MAXFIYAT FROM tablo_adi

   --MIN() FUNCTION
   SELECT MIN(FIYAT) AS MINFIYAT FROM tablo_adi

   --SUM() FUNCTION
   SELECT SUM() AS TOPFIYAT FROM tablo_adi


   /* SCALAR FUNCTION
   LCASE(),
   LEN(),
   MID(),
   NOW(),
   FORMAT(),
   ROUND(),
   UCASE()
   */

   --LCASE() FUNCTION
   SELECT LCASE(MLZADI) AS MLZKUCUK FROM tablo_adi

   --LEN() FUNCTION
   SELECT LEN(MLZADI) AS MLZASDIUZUN FROM tablo_adi

   --MID() FUNCTION
   SELECT MID(MLZADI,1,3) AS MLZADIILKUC FROM tablo_adi

   --NOW() FUNCTION
   SELECT NOW() AS TARIHSAAT

   --FORMAT() FUNCTION
   SELECT MLZID,MLZADI,FIYAT ,FORMAT(NOW(),'DD.MM.YYYY') AS TARIH FROM tablo_adi

   --ROUND() FUNCTION 
   SELECT ROUND(FIYAT,0) AS TAMFIYAT FROM tablo_adi

   --UCASE FUNCTION
   SELECT UCASE(MLZADI) AS MLZBUYUK FROM tablo_adi