

-- USING GROUP BY, HAVÝNG AND ORDER BY


SELECT U.USERNAME AS KULLANICI ADI , U.NAMESURNAME AS ADSOYAD, U.EMAIL AS EMAIL , U.TEL1 AS TELEFON1, U.TEL2 AS TELEFON2,
COUNT(A.ID) AS ADRESSAYISI
FROM TABLO_ADÝ U
JOIN TABLO_ADÝ1 A ON U.ID = A.USERID
JOIN TABLO_ADÝ2 C ON C.ID = A.CITYID
JOIN TABLO_ADÝ3 T ON T.ID = A.TOWNID
JOIN TABLO_ADÝ4 D ON D.ID = A.DISTRICTID
WHERE U.ID=1
GROUP BY U.USERNAME, U.NAMESURNAME , U.EMAIL, U.TEL1, U.TEL2

-----------------------------------------
SELECT U.USERNAME AS KULLANICI ADI , U.NAMESURNAME AS ADSOYAD, U.EMAIL AS EMAIL , U.TEL1 AS TELEFON1, U.TEL2 AS TELEFON2,
COUNT(A.ID) AS ADRESSAYISI
FROM TABLO_ADÝ U
JOIN TABLO_ADÝ1 A ON U.ID = A.USERID
JOIN TABLO_ADÝ2 C ON C.ID = A.CITYID
JOIN TABLO_ADÝ3 T ON T.ID = A.TOWNID
JOIN TABLO_ADÝ4 D ON D.ID = A.DISTRICTID
GROUP BY U.USERNAME, U.NAMESURNAME , U.EMAIL, U.TEL1, U.TEL2
HAVING COUNT(A.ID)=1

-----------------------------------------
SELECT U.USERNAME AS KULLANICI ADI , U.NAMESURNAME AS ADSOYAD, U.EMAIL AS EMAIL , U.TEL1 AS TELEFON1, U.TEL2 AS TELEFON2,
COUNT(A.ID) AS ADRESSAYISI
FROM TABLO_ADÝ U
JOIN TABLO_ADÝ1 A ON U.ID = A.USERID
JOIN TABLO_ADÝ2 C ON C.ID = A.CITYID
JOIN TABLO_ADÝ3 T ON T.ID = A.TOWNID
JOIN TABLO_ADÝ4 D ON D.ID = A.DISTRICTID
GROUP BY U.USERNAME, U.NAMESURNAME , U.EMAIL, U.TEL1, U.TEL2
ORDER BY COUNT(A.ID) DESC